---
title: "Final Notebook"
author: "Jared Parsons"
date: "5/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


# The goal of this project was to create three separate functions within the existing code. My role was to make a functional pathway and integration site so that
when group members were finished with their piece of the puzzle, they would have little difficulty getting it onto Github which was our primary workplace. I was 
able to help our members have ease of access to the code and to one anothers work. I was able to fork and set up forks for every group member where I waas able to 
get a group message set up so members could communicate with one another and myself for when they were actually working on the project. Thus we had a communication
network working where members could then pull the latest update, work on their part and push their work to the Github Repository. I was able to work with each group 
individualy and help get them pointed towards a direction and we were able to work together to get each of their functions integrated sucessfully into the code. 
Overall we were able to get the  save button added to the main page with Carson and Riley's project, fix a csv file issue with Sophie and Noah's group, and finally 
had a slope function that can be added directly into the code at a later date, or used independently.

